localizer:
    files:
        path_loss_file: "pathLoss.csv"
        GP_file: "GP"
    topics:
        output:
            particlecloud_topic: "localizer/particles"
            pose_topic: "localizer/pose"
    frames:
        # Refer to http://wiki.ros.org/amcl
        map_frame: "map_frame"
        odometry_frame: "odom_frame"
        base_frame: "base_frame"
        
    parameters:
        x_min: -20
        x_max: 20
        y_min: -20
        y_max: 20
        n_particles: 3000
        rotational_noise: 0.1
        translational_noise: 0.05
        resample_threshold: 0.1
        lower_limit: -95
