receiver:
  option: 1 # 1: wpa_supplicant; 2: iwlist; 3: monitor mode - tcpdump (currently not implemented)
  wait_time: 1 # Used to control output frequency
  interface: "wlp4s0" # Network interface which can be found by run iwconfig on terminal
  pass_code: "128ve9800" # Pass code to run sudo command
  output_topic: "rss_data_topic" # Output rss data topic
  target_frame: "dummy_parent_frame" # Target frame
  source_frame: "dummy_child_frame" # Source frame, to get transform from source to target frame



    