receiver:
  wait_time: 0.5 # Used to control output frequency
  interface: "wlp4s0" # Network interface which can be found by run iwconfig on terminal
  pass_code: "128ve9800" # Pass code to run sudo command
  output_topic: "rss_data_topic" # Output rss data topic
  target_frame: "map" # Target frame
  source_frame: "base_link" # Source frame, to get transform from source to target frame
