simulation:
  option: False # True to publish dummy odometry data, False to publish dummy tf data
  dummy_odometry_topic: "dummy_odometry_topic"
  dummy_child_frame: "dummy_child_frame"  # From child to parent
  dummy_parent_frame: "dummy_parent_frame"